from src.briefing.schemas import StartupActionBrief


def render_action_brief_markdown(brief: StartupActionBrief) -> str:
    lines: list[str] = [
        f"# Startup Action Brief: {brief.startup_name}",
        "",
        f"**Verdict:** {brief.verdict.value}  ",
        f"**Priority Score:** {brief.final_priority_score}/100  ",
        f"**Motion:** {brief.recommended_motion}  ",
        f"**Confidence:** {brief.confidence.value}  ",
        "",
        "---",
        "",
    ]

    for section in brief.sections:
        lines.append(f"## {section.title}")
        lines.append("")
        if section.items:
            for item in section.items:
                lines.append(
                    f"- **[{item.tag}]** {item.claim} " f"({item.confidence}, {item.source_type})"
                )
        if section.content:
            lines.append(section.content)
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by NVIDIA Startup AI Radar — Epic 10: Startup Action Brief*")

    return "\n".join(lines)
