"""Collect evidence by fetching URLs from a search plan and extracting clean text.

Consumes the structured ``search_plan`` dict generated by ``plan_search``,
respecting ``rate_limit_policy``, ``max_sources``, and ``max_depth``.

Also provides ``collect_governed_sources`` which uses ``HttpSourceCollector``
governed by Source Registry + Decision Calibration — only collects from
production_enabled=true sources with compliance, robots, rate limits,
and calibrated timeout/retry/backoff.
"""

from __future__ import annotations

import time
from datetime import UTC, datetime
from typing import Any


def collect_sources(
    search_plan: dict[str, Any] | list[dict[str, str]],
) -> tuple[list[dict[str, Any]], list[str]]:
    from src.scraping.fetcher import fetch_page
    from src.scraping.parser import extract_clean_text

    evidence_items: list[dict[str, Any]] = []
    errors: list[str] = []

    if isinstance(search_plan, list):
        queries = search_plan
        max_sources = 10
        max_depth = 2
        rate_limit_policy: dict[str, Any] = {"requests_per_second": 2, "concurrent_requests": 1}
    else:
        queries = search_plan.get("search_queries", [])
        max_sources = search_plan.get("max_sources", 10)
        max_depth = search_plan.get("max_depth", 2)
        rate_limit_policy = search_plan.get("rate_limit_policy", {})

    requests_per_second = rate_limit_policy.get("requests_per_second", 2)
    min_interval = 1.0 / max(requests_per_second, 0.5)

    urls_to_fetch = queries[:max_sources]

    last_request_time = 0.0

    for entry in urls_to_fetch:
        url = entry.get("url", "") if isinstance(entry, dict) else entry
        if not url:
            continue

        now = time.monotonic()
        elapsed = now - last_request_time
        if elapsed < min_interval and last_request_time > 0:
            time.sleep(min_interval - elapsed)
        last_request_time = time.monotonic()

        try:
            result = fetch_page(url)
            fetched_at = datetime.now(UTC).isoformat()
            item: dict[str, Any] = {
                "url": url,
                "text": "",
                "source_type": (
                    entry.get("source_type", "unknown") if isinstance(entry, dict) else "unknown"
                ),
                "reason": (entry.get("reason", "") if isinstance(entry, dict) else ""),
                "fetched_at": fetched_at,
                "status_code": result.status,
                "max_depth": max_depth,
            }

            if result.error:
                errors.append(f"{url}: {result.error}")
                continue

            text = extract_clean_text(result.raw_html)
            if text.strip():
                item["text"] = text
                evidence_items.append(item)
            else:
                errors.append(f"{url}: empty content after parsing")
        except Exception as exc:
            errors.append(f"{url}: {type(exc).__name__}: {exc}")

    return evidence_items, errors


def collect_governed_sources(
    startup_name: str,
    website_url: str,
    run_id: str | None = None,
    dry_run: bool = False,
) -> tuple[list[dict[str, Any]], list[str]]:
    """Collect evidence using HttpSourceCollector governed by Source Registry.

    Only fetches from ``production_enabled=true`` sources in the Source
    Registry. Dynamic ``base_url`` is set for per-startup source types
    (e.g. ``startup_official_website`` receives the provided ``website_url``).

    Respects compliance (login, paywall, priority), robots.txt, rate limits,
    and calibrated timeout/retry/backoff from Decision Calibration Registry.

    Args:
        startup_name: Name of the startup (for metadata/logging).
        website_url: Official website URL — used as ``base_url`` for
            startup-specific source records.
        run_id: Optional run identifier. Auto-generated if not provided.
        dry_run: If True, validate compliance without fetching content.

    Returns:
        Tuple of ``(evidence_items, errors)``. Each evidence item is a dict
        with keys: ``url``, ``text``, ``source_type``, ``source_id``,
        ``reason``, ``fetched_at``, ``status_code``, ``content_hash``,
        ``latency_ms``, ``content_bytes``. Compatible with downstream
        consumers (extractor_agent, classifier_agent, etc.).
    """
    from src.scraping.http_collector import (
        CollectionRequest,
        HttpSourceCollector,
        list_governed_sources,
    )

    effective_run_id = run_id or f"governed-{startup_name}-{datetime.now(UTC).isoformat()}"

    records = list_governed_sources()
    if not records:
        return [], ["No production-enabled sources available"]

    populated: list[Any] = []
    for src in records:
        url = (src.base_url or "").strip()
        if not url and src.source_category == "official_website":
            url = website_url
        if not url:
            continue
        populated.append(src.model_copy(update={"base_url": url}))

    if not populated:
        return [], ["No collectable sources after URL resolution"]

    collector = HttpSourceCollector()
    request = CollectionRequest(
        run_id=effective_run_id,
        source_records=populated,
        dry_run=dry_run,
    )

    result = collector.collect(request)

    evidence_items: list[dict[str, Any]] = []
    errors: list[str] = []

    for sfr in result.sources:
        if sfr.status == "fetched" and sfr.raw_html:
            item: dict[str, Any] = {
                "url": sfr.source_url,
                "text": sfr.extracted_text or "",
                "source_type": sfr.metadata.get("source_category", "unknown"),
                "source_id": sfr.source_id,
                "reason": sfr.metadata.get("source_name", ""),
                "fetched_at": sfr.fetched_at.isoformat(),
                "status_code": sfr.http_status_code,
                "content_hash": sfr.content_hash,
                "latency_ms": sfr.latency_ms,
                "content_bytes": sfr.content_bytes,
                "extraction_status": sfr.extraction_status,
            }
            if sfr.extracted_text:
                evidence_items.append(item)
            else:
                errors.append(f"{sfr.source_url}: empty content after extraction")
        elif sfr.status == "blocked":
            code = sfr.error_code or "blocked"
            msg = sfr.error_message_sanitized or code
            errors.append(f"{sfr.source_url}: {code} — {msg}")
        elif sfr.status == "failed":
            msg = sfr.error_message_sanitized or "unknown error"
            errors.append(f"{sfr.source_url}: {msg}")
        elif sfr.status == "duplicate":
            evidence_items.append(
                {
                    "url": sfr.source_url,
                    "text": sfr.extracted_text or "",
                    "source_type": sfr.metadata.get("source_category", "unknown"),
                    "source_id": sfr.source_id,
                    "reason": sfr.metadata.get("source_name", ""),
                    "fetched_at": sfr.fetched_at.isoformat(),
                    "status_code": sfr.http_status_code,
                    "content_hash": sfr.content_hash,
                    "latency_ms": sfr.latency_ms,
                    "content_bytes": 0,
                    "extraction_status": "duplicate_skipped",
                }
            )

    return evidence_items, errors
